version: '3.3'

services:
  pgdb:
    container_name: pgdb
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - ./LandingPage/LandingPage/.env.pgdb
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${NAME}
    volumes:
      - ./LandingPage/pgdata:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    image: landing_backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./LandingPage/:/backend
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

#  frontend:
#    container_name: frontend
#    build:
#      dockerfile: LandingPage/Frontend/Dockerfile
#    command: npm run server
#    ports:
#      - "5173:5173"