# Generated by Django 4.2.7 on 2023-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Доход в час'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=models.FloatField(verbose_name='Доход в месяц'),
        ),
    ]
