# Generated by Django 4.2.7 on 2023-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт')),
                ('message', models.TextField(max_length=2000, verbose_name='Сообщение')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Сообщение посетителя',
                'verbose_name_plural': 'Сообщения посетителей',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='hourly_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Доход в час'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=models.FloatField(verbose_name='Доход в месяц'),
        ),
    ]
