# Generated by Django 4.2.7 on 2023-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_visitormessage_alter_user_hourly_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitormessage',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
